index:
    pattern:  /
    defaults: { _controller: StudenciakBundle:Page:index }

przedmiot:
    path:     /przedmiot
    defaults: { _controller: StudenciakBundle:Page:przedmiot }

repo:
    path:     /repo
    defaults: { _controller: StudenciakBundle:Page:repo }

grupy:
    path:     /grupy
    defaults: { _controller: StudenciakBundle:Page:grupy }

osoby:
    path:     /osoby
    defaults: { _controller: StudenciakBundle:Page:osoby }

dziennik:
    path:     /dziennik
    defaults: { _controller: StudenciakBundle:Page:dziennik }

profil:
    path:     /profil
    defaults: { _controller: StudenciakBundle:Page:profil }

logout:
    path:     /logout
    defaults: { _controller: StudenciakBundle:Page:logout }

login:
    path:     /login
    defaults: { _controller: StudenciakBundle:Page:login }

loginAjax:
    pattern:  /update/data/from/ajax/call
    defaults: { _controller: StudenciakBundle:Page:loginAjax }

logoutSession:
    path:     /logoutSession
    defaults: { _controller: StudenciakBundle:Page:logoutSession }

osobaUsun:
    path: /osoby/usun/{id}
    defaults: { _controller: StudenciakBundle:Page:osobaUsun }

osobaUsuwanie:
    path: /usuwanie/{id}
    defaults: { _controller: StudenciakBundle:Page:osobaUsuwanie }

osobaAdmin:
    path: /osoby/admin/{tryb}/{id}
    defaults: { _controller: StudenciakBundle:Page:osobaAdmin }  

aktywuj:
    path: /osoby/aktywuj/{id}
    defaults: { _controller: StudenciakBundle:Page:aktywuj }

przedmiotDodaj:
    path: /przedmiot/dodaj
    defaults: { _controller: StudenciakBundle:Page:przedmiotDodaj }

przedmiotPokaz:
    path: /przedmiot/pokaz/{id}
    defaults: { _controller: StudenciakBundle:Page:przedmiotPokaz }

przedmiotZapiszSie:
    path: /przedmiot/zapisz/{id}
    defaults: { _controller: StudenciakBundle:Page:przedmiotZapiszSie }

przedmiotDodajZajecia:
    path: /przedmiot/zajecia/dodaj/{id_przedmiotu}
    defaults: { _controller: StudenciakBundle:Page:przedmiotDodajZajecia }

zajeciaPokaz:
    path: /zajecia/{id}
    defaults: { _controller: StudenciakBundle:Page:zajeciaPokaz }

zajeciaDodaj:
    path: /zajecia/dodaj/{id}
    defaults: { _controller: StudenciakBundle:Page:zajeciaDodaj }

zajeciaZapiszSie:
    path: /zajecia/zapisz/{id}
    defaults: { _controller: StudenciakBundle:Page:zajeciaZapiszSie }

repoDodaj:
    path: /repo/dodaj
    defaults: { _controller: StudenciakBundle:Page:repoDodaj }



test:
    path: /test/{id}
    defaults: { _controller: StudenciakBundle:Page:test }